[package]
name = "gitserver"
version = "0.1.0"
authors = ["Maarten de Jonge <mdejonge1990@gmail.com>"]

[dependencies]
git2 = "0.7"
iron = "0.6.*"
router = "*"
staticfile = "*"
mount = "*"
url = "1.7.*"
